#!/usr/bin/env python3
"""Insert food_csv_market_items() into packages/core/src/marketData.generated.ts before demo rows."""

from __future__ import annotations

import json
import sys
from pathlib import Path

_SCRIPTS = Path(__file__).resolve().parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))
from food_market_lib import food_csv_market_items  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
TS_PATH = ROOT / "packages" / "core" / "src" / "marketData.generated.ts"
NEEDLE = '  {\n    id: "demo_agriora_ml_sell_rice"'


def ts_string(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def emit_food_ts(items: list[dict]) -> str:
    lines: list[str] = []
    for it in items:
        obs_chunks = []
        for o in it["observations"]:
            low = "null" if o["low"] is None else repr(o["low"])
            high = "null" if o["high"] is None else repr(o["high"])
            obs_chunks.append(
                f"{{ dateIso: {ts_string(o['dateIso'])}, low: {low}, high: {high} }}"
            )
        obs_js = "[" + ", ".join(obs_chunks) + "]"
        lines.append("  {")
        lines.append(f"    id: {ts_string(it['id'])},")
        lines.append(f"    excelRow: {it['excelRow']},")
        lines.append(f"    group: {ts_string(it['group'])},")
        lines.append(f"    mainCategory: {ts_string(it['mainCategory'])},")
        lines.append(f"    category: {ts_string(it['category'])},")
        lines.append(f"    itemCategory: {ts_string(it['itemCategory'])},")
        lines.append(f"    itemDetails: {ts_string(it['itemDetails'])},")
        lines.append(f"    observations: {obs_js},")
        lines.append("  },")
    return "\n".join(lines)


def main() -> None:
    food = food_csv_market_items()
    text = TS_PATH.read_text(encoding="utf-8")
    if food and food[0]["id"] in text:
        print(f"Food rows already present in {TS_PATH.name}; skip")
        return
    if NEEDLE not in text:
        raise SystemExit(f"Could not find demo row anchor in {TS_PATH}")
    block = emit_food_ts(food)
    new_text = text.replace(NEEDLE, block + "\n" + NEEDLE, 1)
    hdr = (
        "/** Auto-generated by scripts/xlsx_to_market.py — do not edit. "
        "Workbook + optional backend/data/food_*cleaned*.csv + web demo rows (Demo sell / neutral / hold). */"
    )
    if "food_*cleaned*" not in new_text.split("\n", 1)[0]:
        new_text = hdr + "\n" + new_text.split("\n", 1)[1]
    TS_PATH.write_text(new_text, encoding="utf-8")
    print(f"Merged {len(food)} food series into {TS_PATH}")


if __name__ == "__main__":
    main()
