#!/usr/bin/env python3
"""
Read root data.xlsx (Myanmar ag market lows/highs by date) and emit
packages/core/src/marketData.generated.ts for @agriora/core.

The app’s Rice tab uses @agriora/core `RICE_MARKET_ITEMS`: rows whose
item category or detail contains စပါး / ဆန် (see riceMarket.ts). If none,
demo rice series use the same date columns as this export.

Usage (from repo root, with venv + openpyxl):
  .venv/bin/pip install -r requirements-market.txt
  .venv/bin/python scripts/xlsx_to_market.py
"""

from __future__ import annotations

import hashlib
import json
import re
from datetime import date, datetime, timezone
from pathlib import Path

from openpyxl import load_workbook

ROOT = Path(__file__).resolve().parents[1]
XLSX = ROOT / "data.xlsx"
OUT = ROOT / "packages" / "core" / "src" / "marketData.generated.ts"


def ts_string(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def parse_header_date(cell) -> str:
    if cell is None:
        return ""
    if isinstance(cell, datetime):
        return cell.date().isoformat()
    if isinstance(cell, date):
        return cell.isoformat()
    raw = str(cell).strip()
    raw = re.sub(r"\s+", "", raw)
    raw = re.sub(r"^XX-", "31-", raw, flags=re.IGNORECASE)
    for fmt in ("%d-%m-%Y", "%d/%m/%Y", "%Y-%m-%d"):
        try:
            return datetime.strptime(raw, fmt).date().isoformat()
        except ValueError:
            continue
    return raw


def is_number(x) -> bool:
    return isinstance(x, (int, float)) and x is not None


def stable_id(parts: tuple[str, ...]) -> str:
    h = hashlib.sha256("|".join(parts).encode("utf-8")).hexdigest()
    return h[:16]


def main() -> None:
    if not XLSX.is_file():
        raise SystemExit(f"Missing {XLSX}")

    wb = load_workbook(XLSX, data_only=True)
    ws = wb.active
    low_cols = [
        c for c in range(1, (ws.max_column or 0) + 1)
        if ws.cell(2, c).value == "Lowest Price"
    ]
    if not low_cols:
        raise SystemExit("Could not find 'Lowest Price' header row")

    periods_iso = [parse_header_date(ws.cell(1, c).value) for c in low_cols]

    filled: list[str | None] = [None, None, None, None, None]
    items: list[dict] = []

    for r in range(3, (ws.max_row or 0) + 1):
        a, b, c, d, e = (ws.cell(r, i).value for i in range(1, 6))
        for i, v in enumerate([a, b, c, d, e]):
            if v is not None and str(v).strip():
                filled[i] = str(v).strip()
        if e is None or not str(e).strip():
            continue

        item_detail = str(e).strip()
        group = filled[0] or ""
        main_category = filled[1] or ""
        category = filled[2] or ""
        item_category = filled[3] or ""

        observations: list[dict] = []
        for idx, lc in enumerate(low_cols):
            lo = ws.cell(r, lc).value
            hi = ws.cell(r, lc + 1).value
            low_v = float(lo) if is_number(lo) else None
            high_v = float(hi) if is_number(hi) else None
            if low_v is None and high_v is None:
                continue
            observations.append(
                {
                    "dateIso": periods_iso[idx],
                    "low": low_v,
                    "high": high_v,
                }
            )

        if not observations:
            continue

        parts = (group, main_category, category, item_category, item_detail, str(r))
        item_id = stable_id(parts)

        items.append(
            {
                "id": item_id,
                "excelRow": r,
                "group": group,
                "mainCategory": main_category,
                "category": category,
                "itemCategory": item_category,
                "itemDetails": item_detail,
                "observations": observations,
            }
        )

    generated_at = (
        datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    )

    lines = [
        "/** Auto-generated by scripts/xlsx_to_market.py — do not edit. */",
        "",
        'import type { MarketItem } from "./marketTypes";',
        "",
        f"export const MARKET_SOURCE_FILE = {ts_string('data.xlsx')};",
        f"export const MARKET_GENERATED_AT_ISO = {ts_string(generated_at)};",
        "",
        "export const MARKET_PERIODS_ISO: readonly string[] = [",
        *[f"  {ts_string(p)}," for p in periods_iso],
        "];",
        "",
        "export const MARKET_ITEMS: readonly MarketItem[] = [",
    ]

    for it in items:
        obs_chunks = []
        for o in it["observations"]:
            low = "null" if o["low"] is None else repr(o["low"])
            high = "null" if o["high"] is None else repr(o["high"])
            obs_chunks.append(
                f"{{ dateIso: {ts_string(o['dateIso'])}, low: {low}, high: {high} }}"
            )
        obs_js = "[" + ", ".join(obs_chunks) + "]"
        lines.append("  {")
        lines.append(f"    id: {ts_string(it['id'])},")
        lines.append(f"    excelRow: {it['excelRow']},")
        lines.append(f"    group: {ts_string(it['group'])},")
        lines.append(f"    mainCategory: {ts_string(it['mainCategory'])},")
        lines.append(f"    category: {ts_string(it['category'])},")
        lines.append(f"    itemCategory: {ts_string(it['itemCategory'])},")
        lines.append(f"    itemDetails: {ts_string(it['itemDetails'])},")
        lines.append(f"    observations: {obs_js},")
        lines.append("  },")

    lines.append("];")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(items)} items, {len(periods_iso)} periods → {OUT}")


if __name__ == "__main__":
    main()
